### ISSUE TITLE
Add form widgets to booking form

### ISSUE THREAD

**Issue by James-Burch** [James-Burch/PP4-Django-Project#14]
- Add dropdown selection boxes for a site user to select a date they want to play
- Add a selection of booking times a user can choose from that come every 12 minutes

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the BookingForm in forms.py to use SelectDateWidget for date selection and added a choices list for time selection with 12-minute intervals. Updated the booking_view in views.py to handle the new form. Adjusted the bookingpage.html template to display the new dropdown selections.

You can review changes in this commit: https://github.com/lattaai13/James-Burch-PP4-Django-Project-14/commit/d2fb2f22a78cc3f1fae55b89eaf284db7ab4bce9.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
